name: CI/CD MLflow Diabetes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      # 3. Install MLflow & Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          
      # 4. Run MLflow Project
      # Kita masuk ke folder MLProject karena file MLProject ada di sana
      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local
      
      # 5. Get latest run_id (Trickier part)
      # MLflow secara default menyimpan runs di ./mlruns relatif terhadap tempat dijalankan
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          cd MLProject
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Found Run ID: $RUN_ID"
          
      # 6. Build Docker Model using MLflow
      # Pastikan path model-uri benar (runs:/RUN_ID/model)
      # --name "diabetes-model" adalah nama image lokal
      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "diabetes-model"

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 8. Tag Docker Image
      # Format: username_dockerhub/nama_image:tag
      - name: Tag Docker Image
        run: |
          docker tag diabetes-model ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-model:latest

      # 9. Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-model:latest