name: CI/CD MLflow Diabetes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      # 3. Install MLflow & Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn numpy
          
      # 4. Run MLflow Project
      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local
      
      # 5. Get latest run_id (PERBAIKAN: Menggunakan Python)
      # Cara ini jauh lebih akurat daripada menggunakan ls/cut
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          cd MLProject
          # Script python inline untuk mengambil Run ID terakhir
          RUN_ID=$(python -c "import mlflow; runs = mlflow.search_runs(experiment_ids=['0']); print(runs.iloc[0]['run_id'])")
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Succesfully found Run ID: $RUN_ID"
          
      # 6. Build Docker Model using MLflow
      - name: Build Docker Model
        # Kita tambahkan --install-mlflow agar docker image punya mlflow di dalamnya
        run: |
          cd MLProject
          echo "Building Docker for Model URI: runs:/${{ env.RUN_ID }}/model"
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "diabetes-model" --install-mlflow

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 8. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag diabetes-model ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-model:latest

      # 9. Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-model:latest